### ISSUE TITLE
Link to next suggested article

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/contentz#6]
**Is your feature request related to a problem? Please describe.**
It would be great if I could add a `next: /articles/my-next-article` in the frontmatter and Contentz generate a box suggesting to read that link next.

**Describe the solution you'd like**
Something similar to ZEIT documentation

![image](https://user-images.githubusercontent.com/1312018/53765742-e341b580-3e9e-11e9-8053-14f28c7c97e7.png)

**Describe alternatives you've considered**
Maybe define next as an object with link, title and copy.

```yml
next:
  - title: My Next Article
    path: /articles/my-next-article
    description: Read my next article to learn more about this topic.
```
