### ISSUE TITLE
Translated Articles support

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/contentz#7]
**Is your feature request related to a problem? Please describe.**
Contentz should support the idea that an article may be translated and let define if it was translated from or it has been translated to.

**Describe the solution you'd like**
In the original article I want to add something like this:
```yml
translatedTo:
  - lang: en
    path: /articles/en/my-post
  - lang: br
    path: /articles/es/my-post
```

In the translated articles something like this:

```yml
translatedFrom:
  lang: es
  path: /articles/my-post
```

This should be rendered in the UI of the articles to show the possible translations or the original one
